version: "3.7"
services:
  boot-build-image:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./gradlew bootBuildImage
    working_dir: /usr/app
    volumes:
      - ${PWD}:/usr/app/
      - /var/run/docker.sock:/var/run/docker.sock