version: "3.7"
services:
  bootBuildImage:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./gradlew bootBuildImage
    working_dir: /usr/app
    volumes:
      - ${PWD}:/usr/app/