version: "3.7"
services:
  boot-build-image:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./gradlew pushImageToGCR
    working_dir: /usr/app
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BUILDKITE_BUILD_NUMBER
      - ${HOME}/.google-credentials:/.google-credentials
    volumes:
      - ${PWD}:/usr/app/
      - /var/run/docker.sock:/var/run/docker.sock